
LOCAL_SRC_FILES += \
			bhook/bh_core.c \
			bhook/bh_dl.c \
			bhook/bh_dl_iterate.c \
			bhook/bh_dl_monitor.c \
			bhook/bh_elf.c \
			bhook/bh_elf_manager.c \
			bhook/bh_hook.c \
			bhook/bh_hook_manager.c \
			bhook/bh_linker.c \
			bhook/bh_log.c \
			bhook/bh_sleb128.c \
			bhook/bh_task.c \
			bhook/bh_task_manager.c \
			bhook/bh_trampo.c \
			bhook/bh_trampo_arm.c \
			bhook/bh_trampo_arm64.c \
			bhook/bh_trampo_x86.c \
			bhook/bh_trampo_x86_64.c \
			bhook/bh_util.c \
			bhook/bytehook.c \
			bhook/bytesig.c

LOCAL_SRC_FILES += \
			safelog/safe_log.c


LOCAL_C_INCLUDES += \
			$(LOCAL_PATH)/bhook \
			$(LOCAL_PATH)/bhook/include

LOCAL_C_INCLUDES += \
			$(LOCAL_PATH)/safelog \
